# Generated by Django 2.0.2 on 2018-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject',
            field=models.CharField(default='Not Applicable', max_length=256),
            preserve_default=False,
        ),
    ]
