# Generated by Django 2.0.2 on 2018-06-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_education_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilities',
            options={'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'experience'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile'},
        ),
        migrations.AddField(
            model_name='abilities',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abilities',
            name='category',
            field=models.CharField(choices=[('skills', 'Skills'), ('tools', 'Tools')], max_length=256),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='subject',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
