# Generated by Django 2.0.2 on 2018-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180621_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
