# Generated by Django 2.0.2 on 2018-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_experience_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(default='index/img/star.svg', upload_to='index/img/')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(default='index/img/star.svg', upload_to='index/img/'),
        ),
    ]
