# Generated by Django 2.0.2 on 2018-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180622_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('design', 'Design')], default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
